### ISSUE TITLE
Wrong readme?

### ISSUE THREAD

**Issue by Gargo** [stateman92/AngleGradientView#1]
From your readme:
```
.package(url: "https://github.com/stateman92/VibrancyEffectView", exact: .init(0, 0, 1))
```
If your library requires `VibrancyEffectView` then why don't you include it into your own package?

**Comment by kristofkalai** [comment]
It doesn't require VibrancyEffectView, it's just a mistake there. I fixed it in this PR: https://github.com/stateman92/AngleGradientView/pull/2

Thanks!
