### ISSUE TITLE
Feature request - gradient border

### ISSUE THREAD

**Issue by Gargo** [stateman92/AngleGradientView#4]

**Comment by kristofkalai** [comment]
Can you elaborate it a little bit what do you want? Do you want to use this view as a border e.g. to create a view with a "moving gradient border" let's say?

**Comment by Gargo** [comment]
@stateman92 in my case it is a static button with a static gradient border

**Comment by kristofkalai** [comment]
There are possible solutions but this is not part of this repository. For instance:
- https://stackoverflow.com/q/36836367
- https://stackoverflow.com/q/46633099
- https://stackoverflow.com/q/15193993
